context:
  title: Почему мы?
  subtitle: Наши преимущества
  qualities:
    - title: Безупречная репутация
      icon: trophy
      desc: "Visatourservice (ООО ВТС Консалтинг) оказывает туристические и визовые услуги с 2003-го года, имеет безупречную репутацию, прямые контакты с Генеральными консульствами и туроператорами. В сфере оформления виз и эмиграции - для нас нет нерешаемых вопросов! <br>Самый низкий процент отказов на рынке!"
    - title: Гарантия сервиса!
      icon: guarantee
      reverse: true
      desc: "Решение самых сложных визовых вопросов в самые короткие сроки, гарантированно, открываем визы после отказа."
    - title: Наша цена!
      icon: best-price
      desc: "Мы предлагаем самую низкую цену на рынке, если вы нашли дешевле, мы предложим вам лучшую цену!"
    - title: Работа с регионами
      icon: worldwide
      reverse: true
      desc: "На сегодняшний день нашими услугами пользуются десятки тысяч довольных Клиентов по всей России. Компания активно развивает работу с регионами, вам достаточно подписать договор на сотрудничество, отправить нам документы и ваш заказ в консульстве!"
