context:
  title: О компании
  subtitle: Visatourservice
  intro: "Федеральная сеть паспортно-визовых центров Visatourservice (ООО ВТС Консалтинг) совмещает сразу три вида деятельности:"
  items:
    - icon: inclined-passport
      title: Визовый центр
      desc: Центр по оформлению краткосрочных и долгосрочных виз в более чем 70 стран мира;
    - icon: international-flights
      title: Туристическое агентство
      desc: Туристическое агентство полного цикла - мы имеем партнерские соглашения с более чем 150 туроператорами;
    - icon: desk-globe
      title: Сервисный центр
      desc: Предоставляем бюро переводов, работающее на 55-ти иностранных языках; Клиентам доступны страхование выезжающих за рубеж, приглашение для иностранцев в РФ, оформление срочных загранпаспортов и многое другое.
