context:
  categories:
  - name: Европа
    slug: europe
    tables:
    - country:
        name: Болгария
        code: bg
        startPrice: 4000
      rows:
        - items:
            type: 90 дней
            term: 5 р.д.
            price: 4 000
            documents: "загранпаспорт, фото, справка с работы, финансовая гарантия"
        - items:
            type: 90 дней - срочная
            term: 2-3 р.д.
            price: 7 000!
            documents: "загранпаспорт, фото, справка с работы, финансовая гарантия"
        - items:
            type: на 1 год <span class='condition'>(при отъезженной Болгарской визе)</span>
            term: 5-7 р.д.
            price: 4 000
            documents: "загранпаспорт, фото, справка с работы, финансовая гарантия"
        - items:
            type: на 1 год - срочная <span class='condition'>(при отъезженной Болгарской визе)</span>
            term: 2-3 р.д.
            price: 7 500!
            documents: "загранпаспорт, фото, справка с работы, финансовая гарантия"
        - items:
            type: на 1-5 лет <span class='condition'>(владельцы недвижимости)</span>
            term: 5-7 р.д.
            price: 5 500
            documents: "загранпаспорт, фото, \nсправка с работы, \nфинансовая гарантия + документы на недвижимость"
        - items:
            type: Виза Д
            term: "-"
            price: От 21 500
            documents: уточните у менеджера
        - items:
            type: Для граждан других государств
            term: 7-12 р.д.
            price: 6 500
            documents: паспорт, фото, регистрация в РФ, финансовая гарантия
    - country:
        name: Испания
        code: es
        startPrice: 7000
      rows:
        - items:
            type: до 2-х лет
            term: 4-6 р.д.
            price: 7 000
            documents: "загранпаспорт, фото, справка с работы, финансовая гарантия"
        - items:
            type: до 2-х лет - срочная
            term: 3 р.д. бизн.
            price: 10 200!
            documents: "загранпаспорт, фото, справка с работы, финансовая гарантия + приглашение"
    - country:
        name: Италия
        code: it
        startPrice: 7500
      rows:
        - items:
            type: до года
            term: 5-7 р.д.
            price: 7 500
            documents: "загранпаспорт, фото, справка с работы, финансовая гарантия"
    - country:
        name: Нидерланды
        code: nl
        startPrice: 6000
      rows:
        - items:
            type: до года <span class='condition'>(при наличии двух шенгенов)</span>
            term: 5-7 р.д.
            price: 6 000
            documents: "загранпаспорт, фото, справка с работы, финансовая гарантия"
    - country:
        name: Греция
        code: gr
        startPrice: 6500
      rows:
        - items:
            type: до 3-х лет
            term: 5 р.д.
            price: 6 500
            documents: "загранпаспорт, фото, справка с работы, финансовая гарантия"
    - country:
        name: Франция
        code: fr
        startPrice: 6000
      rows:
        - items:
            type: до 5 лет
            term: 5-7 р.д.
            price: 6 000
            documents: "загранпаспорт, фото, справка с работы, финансовая гарантия"
        - items:
            type: до 5 лет - срочная
            term: 3 р.д.
            price: 11 500!
            documents: "загранпаспорт, фото, справка с работы, финансовая гарантия"
    - country:
        name: Чехия
        code: cz
        startPrice: 6500
      rows:
        - items:
            type: до года
            term: 5 р.д.
            price: 6 500
            documents: "загранпаспорт, фото, справка с работы, финансовая гарантия"
    - country:
        name: Швейцария
        code: ch
        startPrice: 7000
      rows:
        - items:
            type: до года
            term: 5 р.д.
            price: 7 000
            documents: "загранпаспорт, фото, справка с работы, финансовая гарантия"
    - country:
        name: Латвия
        code: lv
        startPrice: 7500
      rows:
        - items:
            type: до года
            term: 5 р.д.
            price: 7 500
            documents: "загранпаспорт, фото, справка с работы, финансовая гарантия"
    - country:
        name: Финляндия
        code: fi
        startPrice: 7000
      rows:
        - items:
            type: до года
            term: 7-10 р.д.
            price: 7 000
            documents: "загранпаспорт, фото, справка с работы, финансовая гарантия"
  - name: Азия
    slug: asia
    tables:
    - country:
        name: Тест-азия
        code: bg
        startPrice: 4000
      rows:
        - items:
            type: 90 дней
            term: 5 р.д.
            price: 4 000
            documents: "загранпаспорт, фото, справка с работы, финансовая гарантия"
        - items:
            type: 90 дней - срочная
            term: 2-3 р.д.
            price: 7 000!
            documents: "загранпаспорт, фото, справка с работы, финансовая гарантия"
        - items:
            type: на 1 год <span class='condition'>(при отъезженной Болгарской визе)</span>
            term: 5-7 р.д.
            price: 4 000
            documents: "загранпаспорт, фото, справка с работы, финансовая гарантия"
        - items:
            type: на 1 год - срочная <span class='condition'>(при отъезженной Болгарской визе)</span>
            term: 2-3 р.д.
            price: 7 500!
            documents: "загранпаспорт, фото, справка с работы, финансовая гарантия"
        - items:
            type: на 1-5 лет <span class='condition'>(владельцы недвижимости)</span>
            term: 5-7 р.д.
            price: 5 500
            documents: "загранпаспорт, фото, \nсправка с работы, \nфинансовая гарантия + документы на недвижимость"
        - items:
            type: Виза Д
            term: "-"
            price: От 21 500
            documents: уточните у менеджера
        - items:
            type: Для граждан других государств
            term: 7-12 р.д.
            price: 6 500
            documents: паспорт, фото, регистрация в РФ, финансовая гарантия
    - country:
        name: Испания
        code: es
        startPrice: 7000
      rows:
        - items:
            type: до 2-х лет
            term: 4-6 р.д.
            price: 7 000
            documents: "загранпаспорт, фото, справка с работы, финансовая гарантия"
        - items:
            type: до 2-х лет - срочная
            term: 3 р.д. бизн.
            price: 10 200!
            documents: "загранпаспорт, фото, справка с работы, финансовая гарантия + приглашение"
    - country:
        name: Италия
        code: it
        startPrice: 7500
      rows:
        - items:
            type: до года
            term: 5-7 р.д.
            price: 7 500
            documents: "загранпаспорт, фото, справка с работы, финансовая гарантия"
    - country:
        name: Нидерланды
        code: nl
        startPrice: 6000
      rows:
        - items:
            type: до года <span class='condition'>(при наличии двух шенгенов)</span>
            term: 5-7 р.д.
            price: 6 000
            documents: "загранпаспорт, фото, справка с работы, финансовая гарантия"
    - country:
        name: Греция
        code: gr
        startPrice: 6500
      rows:
        - items:
            type: до 3-х лет
            term: 5 р.д.
            price: 6 500
            documents: "загранпаспорт, фото, справка с работы, финансовая гарантия"
    - country:
        name: Франция
        code: fr
        startPrice: 6000
      rows:
        - items:
            type: до 5 лет
            term: 5-7 р.д.
            price: 6 000
            documents: "загранпаспорт, фото, справка с работы, финансовая гарантия"
        - items:
            type: до 5 лет - срочная
            term: 3 р.д.
            price: 11 500!
            documents: "загранпаспорт, фото, справка с работы, финансовая гарантия"
    - country:
        name: Чехия
        code: cz
        startPrice: 6500
      rows:
        - items:
            type: до года
            term: 5 р.д.
            price: 6 500
            documents: "загранпаспорт, фото, справка с работы, финансовая гарантия"
    - country:
        name: Швейцария
        code: ch
        startPrice: 7000
      rows:
        - items:
            type: до года
            term: 5 р.д.
            price: 7 000
            documents: "загранпаспорт, фото, справка с работы, финансовая гарантия"
    - country:
        name: Латвия
        code: lv
        startPrice: 7500
      rows:
        - items:
            type: до года
            term: 5 р.д.
            price: 7 500
            documents: "загранпаспорт, фото, справка с работы, финансовая гарантия"
    - country:
        name: Финляндия
        code: fi
        startPrice: 7000
      rows:
        - items:
            type: до года
            term: 7-10 р.д.
            price: 7 000
            documents: "загранпаспорт, фото, справка с работы, финансовая гарантия"
  - name: Америка
    slug: america
    tables:
    - country:
        name: Тест-америка
        code: bg
        startPrice: 4000
      rows:
        - items:
            type: 90 дней
            term: 5 р.д.
            price: 4 000
            documents: "загранпаспорт, фото, справка с работы, финансовая гарантия"
        - items:
            type: 90 дней - срочная
            term: 2-3 р.д.
            price: 7 000!
            documents: "загранпаспорт, фото, справка с работы, финансовая гарантия"
        - items:
            type: на 1 год <span class='condition'>(при отъезженной Болгарской визе)</span>
            term: 5-7 р.д.
            price: 4 000
            documents: "загранпаспорт, фото, справка с работы, финансовая гарантия"
        - items:
            type: на 1 год - срочная <span class='condition'>(при отъезженной Болгарской визе)</span>
            term: 2-3 р.д.
            price: 7 500!
            documents: "загранпаспорт, фото, справка с работы, финансовая гарантия"
        - items:
            type: на 1-5 лет <span class='condition'>(владельцы недвижимости)</span>
            term: 5-7 р.д.
            price: 5 500
            documents: "загранпаспорт, фото, \nсправка с работы, \nфинансовая гарантия + документы на недвижимость"
        - items:
            type: Виза Д
            term: "-"
            price: От 21 500
            documents: уточните у менеджера
        - items:
            type: Для граждан других государств
            term: 7-12 р.д.
            price: 6 500
            documents: паспорт, фото, регистрация в РФ, финансовая гарантия
    - country:
        name: Испания
        code: es
        startPrice: 7000
      rows:
        - items:
            type: до 2-х лет
            term: 4-6 р.д.
            price: 7 000
            documents: "загранпаспорт, фото, справка с работы, финансовая гарантия"
        - items:
            type: до 2-х лет - срочная
            term: 3 р.д. бизн.
            price: 10 200!
            documents: "загранпаспорт, фото, справка с работы, финансовая гарантия + приглашение"
    - country:
        name: Италия
        code: it
        startPrice: 7500
      rows:
        - items:
            type: до года
            term: 5-7 р.д.
            price: 7 500
            documents: "загранпаспорт, фото, справка с работы, финансовая гарантия"
    - country:
        name: Нидерланды
        code: nl
        startPrice: 6000
      rows:
        - items:
            type: до года <span class='condition'>(при наличии двух шенгенов)</span>
            term: 5-7 р.д.
            price: 6 000
            documents: "загранпаспорт, фото, справка с работы, финансовая гарантия"
    - country:
        name: Греция
        code: gr
        startPrice: 6500
      rows:
        - items:
            type: до 3-х лет
            term: 5 р.д.
            price: 6 500
            documents: "загранпаспорт, фото, справка с работы, финансовая гарантия"
    - country:
        name: Франция
        code: fr
        startPrice: 6000
      rows:
        - items:
            type: до 5 лет
            term: 5-7 р.д.
            price: 6 000
            documents: "загранпаспорт, фото, справка с работы, финансовая гарантия"
        - items:
            type: до 5 лет - срочная
            term: 3 р.д.
            price: 11 500!
            documents: "загранпаспорт, фото, справка с работы, финансовая гарантия"
    - country:
        name: Чехия
        code: cz
        startPrice: 6500
      rows:
        - items:
            type: до года
            term: 5 р.д.
            price: 6 500
            documents: "загранпаспорт, фото, справка с работы, финансовая гарантия"
    - country:
        name: Швейцария
        code: ch
        startPrice: 7000
      rows:
        - items:
            type: до года
            term: 5 р.д.
            price: 7 000
            documents: "загранпаспорт, фото, справка с работы, финансовая гарантия"
    - country:
        name: Латвия
        code: lv
        startPrice: 7500
      rows:
        - items:
            type: до года
            term: 5 р.д.
            price: 7 500
            documents: "загранпаспорт, фото, справка с работы, финансовая гарантия"
    - country:
        name: Финляндия
        code: fi
        startPrice: 7000
      rows:
        - items:
            type: до года
            term: 7-10 р.д.
            price: 7 000
            documents: "загранпаспорт, фото, справка с работы, финансовая гарантия"
  - name: Австралия и Новая Зеландия
    slug: australia_and_new_zealand
    tables:
    - country:
        name: Тест-австралия
        code: bg
        startPrice: 4000
      rows:
        - items:
            type: 90 дней
            term: 5 р.д.
            price: 4 000
            documents: "загранпаспорт, фото, справка с работы, финансовая гарантия"
        - items:
            type: 90 дней - срочная
            term: 2-3 р.д.
            price: 7 000!
            documents: "загранпаспорт, фото, справка с работы, финансовая гарантия"
        - items:
            type: на 1 год <span class='condition'>(при отъезженной Болгарской визе)</span>
            term: 5-7 р.д.
            price: 4 000
            documents: "загранпаспорт, фото, справка с работы, финансовая гарантия"
        - items:
            type: на 1 год - срочная <span class='condition'>(при отъезженной Болгарской визе)</span>
            term: 2-3 р.д.
            price: 7 500!
            documents: "загранпаспорт, фото, справка с работы, финансовая гарантия"
        - items:
            type: на 1-5 лет <span class='condition'>(владельцы недвижимости)</span>
            term: 5-7 р.д.
            price: 5 500
            documents: "загранпаспорт, фото, \nсправка с работы, \nфинансовая гарантия + документы на недвижимость"
        - items:
            type: Виза Д
            term: "-"
            price: От 21 500
            documents: уточните у менеджера
        - items:
            type: Для граждан других государств
            term: 7-12 р.д.
            price: 6 500
            documents: паспорт, фото, регистрация в РФ, финансовая гарантия
    - country:
        name: Испания
        code: es
        startPrice: 7000
      rows:
        - items:
            type: до 2-х лет
            term: 4-6 р.д.
            price: 7 000
            documents: "загранпаспорт, фото, справка с работы, финансовая гарантия"
        - items:
            type: до 2-х лет - срочная
            term: 3 р.д. бизн.
            price: 10 200!
            documents: "загранпаспорт, фото, справка с работы, финансовая гарантия + приглашение"
    - country:
        name: Италия
        code: it
        startPrice: 7500
      rows:
        - items:
            type: до года
            term: 5-7 р.д.
            price: 7 500
            documents: "загранпаспорт, фото, справка с работы, финансовая гарантия"
    - country:
        name: Нидерланды
        code: nl
        startPrice: 6000
      rows:
        - items:
            type: до года <span class='condition'>(при наличии двух шенгенов)</span>
            term: 5-7 р.д.
            price: 6 000
            documents: "загранпаспорт, фото, справка с работы, финансовая гарантия"
    - country:
        name: Греция
        code: gr
        startPrice: 6500
      rows:
        - items:
            type: до 3-х лет
            term: 5 р.д.
            price: 6 500
            documents: "загранпаспорт, фото, справка с работы, финансовая гарантия"
    - country:
        name: Франция
        code: fr
        startPrice: 6000
      rows:
        - items:
            type: до 5 лет
            term: 5-7 р.д.
            price: 6 000
            documents: "загранпаспорт, фото, справка с работы, финансовая гарантия"
        - items:
            type: до 5 лет - срочная
            term: 3 р.д.
            price: 11 500!
            documents: "загранпаспорт, фото, справка с работы, финансовая гарантия"
    - country:
        name: Чехия
        code: cz
        startPrice: 6500
      rows:
        - items:
            type: до года
            term: 5 р.д.
            price: 6 500
            documents: "загранпаспорт, фото, справка с работы, финансовая гарантия"
    - country:
        name: Швейцария
        code: ch
        startPrice: 7000
      rows:
        - items:
            type: до года
            term: 5 р.д.
            price: 7 000
            documents: "загранпаспорт, фото, справка с работы, финансовая гарантия"
    - country:
        name: Латвия
        code: lv
        startPrice: 7500
      rows:
        - items:
            type: до года
            term: 5 р.д.
            price: 7 500
            documents: "загранпаспорт, фото, справка с работы, финансовая гарантия"
    - country:
        name: Финляндия
        code: fi
        startPrice: 7000
      rows:
        - items:
            type: до года
            term: 7-10 р.д.
            price: 7 000
            documents: "загранпаспорт, фото, справка с работы, финансовая гарантия"
