context:
  slides:
  - num: 0296
    desc:
      l: '11-19'
      w: '2.5+0.5'
      h: '0.9'
      m: '38'

  - num: 8285
    desc:
      l: '6.5+4'
      w: '2.5+0.5'
      h: '0.6'
      m: '45.3'

  - num: 0916
    desc:
      l: '7.7-13.4'
      w: '2.5+0.5'
      h: '0.9'
      m: '32'

  - num: 8302
    desc:
      l: '11'
      w: '2.5+0.5'
      h: '0.9'
      m: '40'

  - num: 2652
    desc:
      l: '7.6+4'
      w: '2.5+0.5'
      h: '0.6'
      m: '47'

  - num: 9328
    desc:
      l: '7.3+5.5'
      w: '2.5+0.5'
      h: '0.6'
      m: '58.5'

  - num: 2850
    desc:
      l: '12.4'
      w: '2.5+0.5'
      h: '0.7'
      m: '35'

  - num: 9429
    desc:
      l: '11.8'
      w: '3'
      h: '0.9'
      m: '77'

  - num: 4678
    desc:
      l: '8.9-15.2'
      w: '2.54+0.46'
      h: '0.9'
      m: '80.1'

  - num: 9491
    desc:
      l: '6.5+4'
      w: '2.5+0.5'
      h: '0.6'
      m: '51'

  - num: 4693
    desc:
      l: '12-19'
      w: '3'
      h: '0.9'
      m: '73'

  - num: 9631
    desc:
      l: '11.95-18.85'
      w: '2.5+0.5'
      h: '0.9'
      m: '60'

  - num: 5566
    desc:
      l: '12.5'
      w: '2.5+0.5'
      h: '0.7'
      m: '35'

  - num: 9657
    desc:
      l: '18.17-23.47'
      w: '2.75'
      h: '0.6'
      m: '80'

  - num: 6989
    desc:
      l: '11-19'
      w: '2.5+0.5'
      h: '0.9'
      m: '35'


  - num: 4886
    desc:
      l: '14-21'
      w: '2.5+0.5'
      h: '0.9'
      m: '92.6+28.85'

  - num: 1212
    desc:
      l: '9.5-15.5'
      w: '2.55'
      h: '0.6/0.9'
      m: '43.7'

  - num: 9437
    desc:
      l: '9.3-16.3'
      w: '2.54'
      h: '0.9'
      m: '71.8'
