variants:
  - name: country
    context:
      country:
        name: Болгария
        code: bg
      thead:
        type: Тип визы
        term: Срок оформления
        price: "Стоимость под ключ, \nвсе сборы включены (рубли)"
        documents: Список документов
        action: Заявка на оформление
      rows:
